In [2]:
import pandas as pd

In [3]:
path = '/home/alexandre_pantalena/Downloads/CRI_CRA_FixedIncomeCRIInstrumentFileV2_20241024_1.json'

df = pd.read_json(path)
df

,RptDt,TckrSymb,SctyId,SctySrc,MktIdrCd,ISIN,CrpnNm,CrdnlNb,IssdQty,RegnDt,...,CvntChngCd,CollInfoDesc,CvrgChngCd,OTCCollVal,CollSctyDesc,FmzdStznTermInd,IndxrDsplcmntDt,InfoRspnsblNm,OTCPmtAgtNm,DataSts
0,2024-10-24,05J0024381,4771,T,B3,BRBSCSCRI0W3,BRAZILIAN SECURITIES CIA DE SECURITIZACAO,1,685,2008-07-18,...,,,,,,N,,SEM NOME DO RESPONSAVEL,BRAZILIAN SECURIT. CIA DE SECURITIZACAO,I
1,2024-10-24,05J0024391,4769,T,B3,BRBSCSCRI0V5,BRAZILIAN SECURITIES CIA DE SECURITIZACAO,1,2743,2008-07-18,...,,,,,,N,,SEM NOME DO RESPONSAVEL,BRAZILIAN SECURIT. CIA DE SECURITIZACAO,I
2,2024-10-24,07F0006634,4772,T,B3,BRBSCSCRI1U5,BRAZILIAN SECURITIES CIA DE SECURITIZACAO,1,2,2008-07-18,...,,,,,,S,,SEM NOME DO RESPONSAVEL,BRAZILIAN SECURIT. CIA DE SECURITIZACAO,I
3,2024-10-24,07F0006635,4770,T,B3,BRBSCSCRI1T7,BRAZILIAN SECURITIES CIA DE SECURITIZACAO,1,10,2008-07-18,...,,,,,,S,,SEM NOME DO RESPONSAVEL,BRAZILIAN SECURIT. CIA DE SECURITIZACAO,I
4,2024-10-24,07I0012088,4774,T,B3,BRBSCSCRI1X9,BRAZILIAN SECURITIES CIA DE SECURITIZACAO,1,8,2008-07-18,...,,,,,,S,,SEM NOME DO RESPONSAVEL,BRAZILIAN SECURIT. CIA DE SECURITIZACAO,I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3721,2024-10-24,24J2347143,12281,T,B3,BRRBRACRIQ20,OPEA SECURITIZADORA S/A,342,88476,2024-10-11,...,,,,,,S,,FLAVIA PALACIOS MENDONCA BAILUNE,OPEA SECURITIZADORA S/A,I
3722,2024-10-24,24J2347147,12287,T,B3,BRRBRACRIQ38,OPEA SECURITIZADORA S/A,342,141524,2024-10-11,...,,,,,,S,4,FLAVIA PALACIOS MENDONCA BAILUNE,OPEA SECURITIZADORA S/A,I
3723,2024-10-24,24J2417849,12313,T,B3,BRRBRACR0079,OPEA SECURITIZADORA S/A,5,10002,2024-10-14,...,,,,,,S,,FLAVIA PALACIOS MENDONCA BAILUNE,OPEA SECURITIZADORA S/A,I
3724,2024-10-24,24J2479385,12333,T,B3,BRRBRACRIQ46,OPEA SECURITIZADORA S/A,332,16250,2024-10-15,...,,,,,,S,,FLAVIA PALACIOS MENDONCA BAILUNE,OPEA SECURITIZADORA S/A,I
3725,2024-10-24,24J2479470,12334,T,B3,BRRBRACRIQ53,OPEA SECURITIZADORA S/A,332,17375,2024-10-15,...,,,,,,S,0,FLAVIA PALACIOS MENDONCA BAILUNE,OPEA SECURITIZADORA S/A,I

In [4]:
path = '/home/alexandre_pantalena/Downloads/inf_mensal_cri_2024-2024-10-13/inf_mensal_cri_classe_2024.csv'

df = pd.read_csv(path, sep=';', encoding='latin1')
df

,CNPJ_Emissora,Codigo_Identificacao_Certificado,Data_Referencia,Versao,Classe,Numero_Serie,Tipo_Oferta,Codigo_CETIP,Codigo_ISIN,Quantidade,...,Quantidade_Certificados,Valor_Certificados,Rendimentos,Amortizacoes,Rentabilidade,Classificacao_Risco_Atual,Nivel_Subordinacao,Periodicidade_Amortizacao,Indice_Subordinacao_Minimo,Indice_Subordinacao_Data_Base
0,02.105.040/0001-23,14G0412569,2024-01-01,1,Sênior,217,Profissionais,14G0412569,14G0412569,NaN,...,1.0,189940.37,697.75,1302.24,0.01,NaN,NaN,NaN,NaN,NaN
1,02.105.040/0001-23,14G0412569,2024-01-01,1,Subordinada,218,Profissionais,14G0412570,14G0412570,NaN,...,0.0,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN
2,02.105.040/0001-23,14G0412569,2024-02-01,1,Sênior,217,Profissionais,14G0412569,14G0412569,NaN,...,1.0,189940.37,697.75,1302.24,0.01,NaN,NaN,NaN,NaN,NaN
3,02.105.040/0001-23,14G0412569,2024-02-01,1,Subordinada,218,Profissionais,14G0412570,14G0412570,NaN,...,0.0,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN
4,02.105.040/0001-23,14G0412569,2024-03-01,1,Sênior,217,Profissionais,14G0412569,14G0412569,NaN,...,1.0,189940.37,697.75,1302.24,0.01,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28826,51.319.586/0001-92,BRRCKSCRI015,2024-04-01,2,Sênior,1,Profissionais,24D2962583,BRRCKSCRI015,NaN,...,15000.0,15030353.88,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN
28827,51.319.586/0001-92,BRRCKSCRI015,2024-05-01,2,Sênior,1,Profissionais,24D2962583,BRRCKSCRI015,NaN,...,15000.0,15181412.45,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN
28828,51.319.586/0001-92,BRRCKSCRI015,2024-06-01,2,Sênior,1,Profissionais,24D2962583,BRRCKSCRI015,NaN,...,15000.0,15332887.83,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN
28829,51.319.586/0001-92,BRRCKSCRI015,2024-07-01,1,Sênior,1,Profissionais,24D2962583,BRRCKSCRI015,NaN,...,15000.0,28120835.42,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN
28830,51.319.586/0001-92,BRRCKSCRI015,2024-08-01,1,Sênior,1,Profissionais,24D2962583,BRRCKSCRI015,NaN,...,15000.0,28429628.06,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN

In [5]:
df['Classe'].unique()

# 'classe': ['cnpj_emissora', 'codigo_identificacao_certificado', 'data_referencia', 'versao', 'classe'],

array(['Sênior', 'Subordinada', 'Mezanino'], dtype=object)

In [6]:
df[df['Codigo_CETIP'] == '24G1888841']

,CNPJ_Emissora,Codigo_Identificacao_Certificado,Data_Referencia,Versao,Classe,Numero_Serie,Tipo_Oferta,Codigo_CETIP,Codigo_ISIN,Quantidade,...,Quantidade_Certificados,Valor_Certificados,Rendimentos,Amortizacoes,Rentabilidade,Classificacao_Risco_Atual,Nivel_Subordinacao,Periodicidade_Amortizacao,Indice_Subordinacao_Minimo,Indice_Subordinacao_Data_Base
28813,48.415.978/0001-40,BRLSECCRI169,2024-08-01,1,Sênior,1,Profissionais,24G1888841,BRLSECCRI169,NaN,...,9000.0,8875578.04,26242.65,175600.46,0.02,NaN,NaN,NaN,0.0,0.0

In [7]:
df[df['Codigo_Identificacao_Certificado'] == 'BRLSECCRI169']

,CNPJ_Emissora,Codigo_Identificacao_Certificado,Data_Referencia,Versao,Classe,Numero_Serie,Tipo_Oferta,Codigo_CETIP,Codigo_ISIN,Quantidade,...,Quantidade_Certificados,Valor_Certificados,Rendimentos,Amortizacoes,Rentabilidade,Classificacao_Risco_Atual,Nivel_Subordinacao,Periodicidade_Amortizacao,Indice_Subordinacao_Minimo,Indice_Subordinacao_Data_Base
28813,48.415.978/0001-40,BRLSECCRI169,2024-08-01,1,Sênior,1,Profissionais,24G1888841,BRLSECCRI169,NaN,...,9000.0,8875578.04,26242.65,175600.46,0.02,NaN,NaN,NaN,0.0,0.0
28814,48.415.978/0001-40,BRLSECCRI169,2024-08-01,1,Sênior,2,Profissionais,24G1944447,BRLSECCRI177,NaN,...,4000.0,3944701.35,11663.40,78044.65,0.02,NaN,NaN,NaN,0.0,0.0